version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - ./mongo_data:/data/db

  backend:
    image: site_backend
    build:
      context: site-backend
      dockerfile: Dockerfile
      args:
        JAR_FILE: out/site.jar
    restart: always
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - SSL_PASS=${SSL_PASS}
      - SSL_ALIAS=${SSL_ALIAS}
    volumes:
      - /etc/letsencrypt:/data/ssl

  frontend:
    image: site_frontend
    build:
      context: site-frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/data/ssl
